import { DEFAULT_THEME, type Guide } from "@/types/guide";

export const SAMPLE_GUIDE: Guide = {
  id: "sample-1",
  user_id: "demo",
  title: "Portland, Oregon",
  subtitle: "Family Travel Guide · March 2026",
  slug: "portland-2026",
  tags: ["🌲 Pacific NW", "👨‍👩‍👧 Family", "🐾 Dog Friendly", "🍜 Foodie"],
  color_theme: DEFAULT_THEME,
  published: true,
  created_at: "2026-03-01T00:00:00Z",
  updated_at: "2026-03-23T00:00:00Z",
  notices: [
    {
      emoji: "🐾",
      title: "犬連れ情報",
      text: "多くのレストランにはドッグフレンドリーなパティオがあります。水のボウルも用意されていることが多いです。",
    },
    {
      emoji: "🅿️",
      title: "駐車場",
      text: "ダウンタウンではSmartParkが最安。週末は$5のフラットレートの駐車場も。",
    },
    {
      emoji: "🌧️",
      title: "天気",
      text: "3月のポートランドは雨が多い。レインジャケットと防水の靴を忘れずに。",
    },
  ],
  footer_text: "Made with love for our Portland adventure 🌲",
  sections: [
    {
      id: "s1",
      guide_id: "sample-1",
      title: "レストラン",
      section_number: "01",
      nav_label: "レストラン",
      anchor: "restaurants",
      section_type: "cards",
      bg_alt: false,
      sort_order: 0,
      subsections: [
        {
          id: "sub1",
          section_id: "s1",
          title: "🌅 朝食 · ブランチ",
          sort_order: 0,
          spots: [
            {
              id: "spot1",
              subsection_id: "sub1",
              name: "Screen Door",
              description:
                "南部料理のブランチで超有名。プルドポークのベネディクトが絶品。週末は1-2時間待ちも覚悟。",
              image_url: null,
              fallback_emoji: "🍳",
              google_maps_query: "Screen Door Portland OR",
              sort_order: 0,
              badges: [
                { id: "b1", spot_id: "spot1", label: "🐾 犬連れパティオ", badge_type: "dog", sort_order: 0 },
                { id: "b2", spot_id: "spot1", label: "🔥 人気", badge_type: "hot", sort_order: 1 },
              ],
              meta: [
                { id: "m1", spot_id: "spot1", icon: "📍", value: "2337 E Burnside St, Portland", sort_order: 0 },
                { id: "m2", spot_id: "spot1", icon: "🕐", value: "8:00-14:00 (ブランチ)", sort_order: 1 },
                { id: "m3", spot_id: "spot1", icon: "💰", value: "$15-25", sort_order: 2 },
              ],
            },
            {
              id: "spot2",
              subsection_id: "sub1",
              name: "Pip's Original Doughnuts",
              description:
                "小さな手作りドーナツとチャイが名物。サイズが小さいので色々な味を試せる。",
              image_url: null,
              fallback_emoji: "🍩",
              google_maps_query: "Pip's Original Doughnuts Portland",
              sort_order: 1,
              badges: [
                { id: "b3", spot_id: "spot2", label: "☕ テイクアウト", badge_type: "togo", sort_order: 0 },
              ],
              meta: [
                { id: "m4", spot_id: "spot2", icon: "📍", value: "4759 NE Fremont St", sort_order: 0 },
                { id: "m5", spot_id: "spot2", icon: "💰", value: "$5-12", sort_order: 1 },
              ],
            },
          ],
        },
        {
          id: "sub2",
          section_id: "s1",
          title: "🍜 ランチ · ディナー",
          sort_order: 1,
          spots: [
            {
              id: "spot3",
              subsection_id: "sub2",
              name: "Pok Pok",
              description:
                "タイ北部のストリートフードが楽しめる名店。特にフィッシュソースの手羽先が有名。",
              image_url: null,
              fallback_emoji: "🍗",
              google_maps_query: "Pok Pok Portland OR",
              sort_order: 0,
              badges: [
                { id: "b4", spot_id: "spot3", label: "🔥 人気", badge_type: "hot", sort_order: 0 },
                { id: "b5", spot_id: "spot3", label: "🇯🇵 日本語メニュー", badge_type: "jp", sort_order: 1 },
              ],
              meta: [
                { id: "m6", spot_id: "spot3", icon: "📍", value: "3226 SE Division St", sort_order: 0 },
                { id: "m7", spot_id: "spot3", icon: "🕐", value: "17:00-22:00", sort_order: 1 },
                { id: "m8", spot_id: "spot3", icon: "💰", value: "$15-30", sort_order: 2 },
              ],
            },
            {
              id: "spot4",
              subsection_id: "sub2",
              name: "Salt & Straw",
              description:
                "ユニークなフレーバーの手作りアイスクリーム。季節限定フレーバーが毎月変わる。",
              image_url: null,
              fallback_emoji: "🍦",
              google_maps_query: "Salt and Straw Portland NW 23rd",
              sort_order: 1,
              badges: [
                { id: "b6", spot_id: "spot4", label: "🐾 犬連れOK", badge_type: "dog", sort_order: 0 },
                { id: "b7", spot_id: "spot4", label: "🆓 試食無料", badge_type: "free", sort_order: 1 },
              ],
              meta: [
                { id: "m9", spot_id: "spot4", icon: "📍", value: "838 NW 23rd Ave", sort_order: 0 },
                { id: "m10", spot_id: "spot4", icon: "💰", value: "$6-10", sort_order: 1 },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "s2",
      guide_id: "sample-1",
      title: "観光スポット",
      section_number: "02",
      nav_label: "観光",
      anchor: "sightseeing",
      section_type: "cards",
      bg_alt: true,
      sort_order: 1,
      subsections: [
        {
          id: "sub3",
          section_id: "s2",
          title: "🌳 自然 · 公園",
          sort_order: 0,
          spots: [
            {
              id: "spot5",
              subsection_id: "sub3",
              name: "Washington Park",
              description:
                "日本庭園、バラ園、森林公園が集まる広大な公園。一日中楽しめる。",
              image_url: null,
              fallback_emoji: "🌲",
              google_maps_query: "Washington Park Portland",
              sort_order: 0,
              badges: [
                { id: "b8", spot_id: "spot5", label: "🐾 犬連れOK", badge_type: "dog", sort_order: 0 },
                { id: "b9", spot_id: "spot5", label: "🆓 入場無料", badge_type: "free", sort_order: 1 },
              ],
              meta: [
                { id: "m11", spot_id: "spot5", icon: "📍", value: "4033 SW Canyon Rd", sort_order: 0 },
                { id: "m12", spot_id: "spot5", icon: "🕐", value: "5:00-22:00", sort_order: 1 },
              ],
            },
            {
              id: "spot6",
              subsection_id: "sub3",
              name: "Multnomah Falls",
              description:
                "高さ189mの二段滝。ポートランドから車で30分。橋からの眺めが最高。",
              image_url: null,
              fallback_emoji: "🏔️",
              google_maps_query: "Multnomah Falls Oregon",
              sort_order: 1,
              badges: [],
              meta: [
                { id: "m13", spot_id: "spot6", icon: "📍", value: "Historic Columbia River Hwy", sort_order: 0 },
                { id: "m14", spot_id: "spot6", icon: "🚗", value: "ポートランドから車30分", sort_order: 1 },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "s3",
      guide_id: "sample-1",
      title: "イベント",
      section_number: "03",
      nav_label: "イベント",
      anchor: "events",
      section_type: "events",
      bg_alt: false,
      sort_order: 2,
      events: [
        {
          id: "e1",
          section_id: "s3",
          date_label: "26",
          day_label: "水",
          title: "Saturday Market (Wed Edition)",
          description: "ポートランドの名物マーケット。ハンドメイドのクラフトやフード屋台。",
          sort_order: 0,
        },
        {
          id: "e2",
          section_id: "s3",
          date_label: "27",
          day_label: "木",
          title: "Forest Park ハイキング",
          description: "Wildwood Trailの朝ハイキング。約5km、初心者向け。",
          sort_order: 1,
        },
      ],
    },
    {
      id: "s4",
      guide_id: "sample-1",
      title: "おすすめルート",
      section_number: "04",
      nav_label: "ルート",
      anchor: "route",
      section_type: "route",
      bg_alt: true,
      sort_order: 3,
      route_stops: [
        {
          id: "r1",
          section_id: "s4",
          title: "PDX空港到着",
          description: "MAX Light Railでダウンタウンへ（約40分、$2.80）",
          sort_order: 0,
        },
        {
          id: "r2",
          section_id: "s4",
          title: "ホテルチェックイン",
          description: "荷物を置いたら Pearl District を散策",
          sort_order: 1,
        },
        {
          id: "r3",
          section_id: "s4",
          title: "Powell's City of Books",
          description: "世界最大の独立系書店。ブロック全体が書店。地図をもらって探検しよう。",
          sort_order: 2,
        },
        {
          id: "r4",
          section_id: "s4",
          title: "ディナー @ Pok Pok",
          description: "予約推奨。フィッシュソースウィングは必須オーダー。",
          sort_order: 3,
        },
      ],
    },
    {
      id: "s5",
      guide_id: "sample-1",
      title: "スケジュール",
      section_number: "05",
      nav_label: "日程",
      anchor: "schedule",
      section_type: "schedule",
      bg_alt: false,
      sort_order: 4,
      schedule_days: [
        {
          id: "d1",
          section_id: "s5",
          label: "水曜日 · March 26 (Wed)",
          sort_order: 0,
          items: [
            { id: "si1", schedule_day_id: "d1", time_label: "午前", title: "Screen Door でブランチ", description: "8:30到着推奨（待ち時間短め）", sort_order: 0 },
            { id: "si2", schedule_day_id: "d1", time_label: "昼", title: "Washington Park 散策", description: "日本庭園 → バラ園", sort_order: 1 },
            { id: "si3", schedule_day_id: "d1", time_label: "夕方", title: "NW 23rd Ave ショッピング", description: "Salt & Straw のアイスも忘れずに", sort_order: 2 },
            { id: "si4", schedule_day_id: "d1", time_label: "夜", title: "Pok Pok ディナー", description: null, sort_order: 3 },
          ],
        },
        {
          id: "d2",
          section_id: "s5",
          label: "木曜日 · March 27 (Thu)",
          sort_order: 1,
          items: [
            { id: "si5", schedule_day_id: "d2", time_label: "午前", title: "Pip's Doughnuts → Multnomah Falls", description: "ドーナツとチャイをテイクアウトしてドライブ", sort_order: 0 },
            { id: "si6", schedule_day_id: "d2", time_label: "昼", title: "Columbia River Gorge", description: "滝を見ながらハイキング", sort_order: 1 },
            { id: "si7", schedule_day_id: "d2", time_label: "夕方", title: "空港へ → 帰路", description: null, sort_order: 2 },
          ],
        },
      ],
    },
  ],
};
